[project]
name = "photogram-test-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "httpx>=0.28.1",
    "lxml>=5.3.1",
    "requests>=2.32.3",
    "selenium>=4.29.0",
]
